# GitHub PR Automation Configuration
# Copy this file and customize it for your setup

# GitHub Configuration
github:
  token: "your_github_personal_access_token"
  repository: "owner/repository_name"
  base_branch: "main"
  auto_merge: false
  require_reviews: true

# Groq AI Configuration
groq:
  api_key: "your_groq_api_key"
  model: "groq/llama3-8b-8192"
  max_tokens: 2048
  temperature: 0.7

# Google Sheets Configuration
sheets:
  credentials_file: "path/to/credentials.json"
  spreadsheet_id: "your_spreadsheet_id"
  worksheet_name: "PR Tracking"
  auto_sync: true
  sync_interval: 300  # seconds

# Automation Settings
automation:
  check_interval: 3600  # seconds
  max_concurrent_reviews: 5
  auto_comment: true
  review_all_open: true
